# Generated by Django 4.2.13 on 2024-05-30 09:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("steganography", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="payloads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="imageupload",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 5, 30, 9, 15, 3, 197360, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="StegoObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stego_image", models.ImageField(upload_to="stego_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cover_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="steganography.imageupload",
                    ),
                ),
                (
                    "payload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="steganography.payload",
                    ),
                ),
            ],
        ),
    ]
