# Generated by Django 5.0.6 on 2024-05-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0002_payload_imageupload_uploaded_at_stegoobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='StegoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='original/')),
                ('message', models.TextField()),
                ('stego_image', models.ImageField(blank=True, null=True, upload_to='stego/')),
            ],
        ),
    ]
