# Generated by Django 5.0.6 on 2024-05-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0003_stegoimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stegoimage',
            name='original_image',
            field=models.ImageField(upload_to='images/input'),
        ),
        migrations.AlterField(
            model_name='stegoimage',
            name='stego_image',
            field=models.ImageField(blank=True, null=True, upload_to='imgaes/input/withmsg'),
        ),
    ]
