# Generated by Django 5.0.6 on 2024-06-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0004_alter_stegoimage_original_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stegoobject',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='stegoobject',
            name='cover_image',
        ),
        migrations.DeleteModel(
            name='Payload',
        ),
        migrations.DeleteModel(
            name='StegoObject',
        ),
    ]
