# Generated by Django 5.0.6 on 2024-06-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0005_remove_stegoobject_payload_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
