# Generated by Django 5.0.6 on 2024-06-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0006_delete_imageupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stegoimage',
            name='stego_image',
        ),
        migrations.AlterField(
            model_name='stegoimage',
            name='original_image',
            field=models.ImageField(upload_to='stego_images/original'),
        ),
    ]
