# Generated by Django 5.0.6 on 2024-06-07 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0008_stegoimage_stego_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stegoimage',
            name='stego_image',
        ),
    ]
