# Generated by Django 5.0.6 on 2024-06-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0009_remove_stegoimage_stego_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stegoimage',
            name='original_image',
            field=models.ImageField(upload_to='stego_images/original'),
        ),
    ]
