# Generated by Django 5.0.6 on 2024-06-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0010_alter_stegoimage_original_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stegoimage',
            name='stego_image',
            field=models.ImageField(blank=True, null=True, upload_to='stego_images/'),
        ),
    ]
