# Generated by Django 5.0.6 on 2024-06-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0011_stegoimage_stego_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StegoAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_audio', models.FileField(upload_to='stego_audio/original')),
                ('message', models.TextField()),
                ('stego_audio', models.FileField(blank=True, null=True, upload_to='stego_audio/')),
            ],
        ),
    ]
