# Generated by Django 5.0.6 on 2024-06-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0012_stegoaudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='stegoaudio',
            name='message_file',
            field=models.FileField(blank=True, null=True, upload_to='stego_messages'),
        ),
    ]
