# Generated by Django 5.0.6 on 2024-06-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0013_stegoaudio_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='stegoimage',
            name='message_file',
            field=models.FileField(blank=True, null=True, upload_to='stego_messages'),
        ),
    ]
