# Generated by Django 5.0.6 on 2024-06-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0016_stegodecodeaudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stegodecodeimage',
            name='message_file',
        ),
        migrations.AddField(
            model_name='stegodecodeimage',
            name='reader_file',
            field=models.FileField(blank=True, null=True, upload_to='stego_messages'),
        ),
        migrations.AlterField(
            model_name='stegodecodeaudio',
            name='message_file',
            field=models.FileField(blank=True, null=True, upload_to='stego_messages'),
        ),
    ]
