# Generated by Django 5.0.6 on 2024-06-12 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0018_remove_stegoimage_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stegoaudio',
            name='message',
        ),
    ]
