# Generated by Django 5.0.6 on 2024-06-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0019_remove_stegoaudio_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='stegoaudio',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
